TEAM_PROPS = 1
TEAM_HUNTERS = 2

TEAM_PROPS_COLOR = Color(255,0,0,255)
TEAM_HUNTERS_COLOR = Color(0,0,255,255)

TEAM_PROPS_DEFAULT_MODEL = "models/player.mdl"
TEAM_HUNTERS_DEFAULT_MODEL = "models/player/Combine_Super_Soldier.mdl"

PROP_CHOOSE_COOLDOWN = 5
PROP_SELECT_DISTANCE = 150

THIRDPERSON_DISTANCE = 100

USABLE_PROP_ENTITIES = {
	"prop_physics",
	"prop_physics_multiplayer"
}

GOOD_HOVER_COLOR = Color(0,255,0,255)
BAD_HOVER_COLOR = Color(255,0,0,255)